### ISSUE TITLE
Can't run it in Node.js because Node is not defined

### ISSUE THREAD

**Issue by adriaandotcom** [BlackGlory/parse-favicon#7]
When running this in node v14.15.0:

```js
const { parseFavicon } = require("parse-favicon");
const axios = require("axios");

(async () => {
  const pageUrl = "https://github.com";

  parseFavicon(pageUrl, textFetcher, bufferFetcher).subscribe((icon) =>
    console.log(icon)
  );

  async function textFetcher(url) {
    console.log("textFetcher:", url);
    return await axios
      .get(resolveUrl(url, pageUrl), { responseType: "text" })
      .then((res) => {
        return res.data;
      });
  }

  async function bufferFetcher(url) {
    console.log("bufferFetcher:", url);
    return await axios
      .get(resolveUrl(url, pageUrl), { responseType: "arraybuffer" })
      .then((res) => res.data);
  }

  function resolveUrl(url, base) {
    return new URL(url, base).href;
  }
})()
```

I get this error:

```
Sat, 30 Jan 2021 21:21:05 GMT uncaughtException: Node is not defined
ReferenceError: Node is not defined
    at Object.isDocument (.../app/node_modules/@blackglory/types/lib/es2018/dom.js:8:55)
    at Document.query (.../app/node_modules/@blackglory/query/lib/es2018/query.js:6:29)
    at Object.getIcons (.../app/node_modules/parse-favicon/lib/es2018/shared/link-element-utils.js:9:33)
    at Object.parseAppleTouchIcons (.../app/node_modules/parse-favicon/lib/es2018/parse-apple-touch-icons.js:9:33)
    at parse (.../app/node_modules/parse-favicon/lib/es2018/index.js:26:42)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

It refers to this file (with the line `Node.DOCUMENT_NODE`):

```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.isElement = exports.isDocument = void 0;
const object_1 = require("./object");
function isDocument(val) {
    if ('HTMLDocument' in globalThis && val instanceof HTMLDocument)
        return true;
    return object_1.isObject(val) && val.nodeType === Node.DOCUMENT_NODE;
}
exports.isDocument = isDocument;
function isElement(val) {
    if ('HTMLElement' in globalThis && val instanceof HTMLElement)
        return true;
    return object_1.isObject(val) && val.nodeType === Node.ELEMENT_NODE;
}
exports.isElement = isElement;
//# sourceMappingURL=dom.js.map
```

**Comment by BlackGlory** [comment]
This code should work in v3.0.9.

```js
const { parseFavicon } = require("parse-favicon");
const axios = require("axios");

(async () => {
  const pageUrl = "https://github.com";

  parseFavicon(pageUrl, textFetcher, bufferFetcher).subscribe((icon) =>
    console.log(icon)
  );

  async function textFetcher(url) {
    return await axios
      .get(
        resolveUrl(url, pageUrl),
        {
          transformResponse: [],
          responseType: "text"
        }
      )
      .then((res) => {
        return res.data;
      });

  }

  async function bufferFetcher(url) {
    return await axios
      .get(resolveUrl(url, pageUrl), { responseType: "arraybuffer" })
      .then((res) => res.data);
  }

  function resolveUrl(url, base) {
    return new URL(url, base).href;
  }
})()
```

**Comment by adriaandotcom** [comment]
Thanks a lot @BlackGlory! Works great now. Appreciate your (super fast) help!
